### PR TITLE
Revert back to explicit bootstrapping of SELinux configuration

### LINKED ISSUE #1262: Robotest upgrade failure
Version: `7.0.0-rc.2.4`
OS: CentOS 7.x/rhel 7.x

Upgrading fails at `upload` step with the error message:
```
open /path/to/installer/directory/gravity.db: permission denied
```

### PR DESCRIPTION
**Pull request by a-palchikov**
Revert back to explicit bootstrapping of SELinux configuration per operation instead of early bootstrapping for install/join/upgrade.

The change does not matter much for installs/joins but in case of upgrades it allows to avoid unnecessary bootstrapping if the node does not have SELinux support turned on.
Additionally, it avoid the pitfall of having the labeled installer binary and SELinux support off - if that were the case, the binary running in confined context will fail to access resources it does not have access to (incl. access to the state directory which is labeled with a base type instead of the type expected by the installer SELinux domain).

A note on installer operation during upgrade: as previously implemented but discarded, the installer will attempt to determine the state of SELinux support by querying cluster state using the existing gravity binary which aims to avoid the risk of running into a permission denied at the early stage prior to configuring the SELinux configuration for the installer.

Requires https://github.com/gravitational/gravity.e/pull/4283.
Fixes https://github.com/gravitational/gravity/issues/1262.

### CODE REVIEW

File: tool/gravity/cli/config.go [hunk 1]
```diff
@@ -499,6 +502,28 @@ func (i *InstallConfig) RunLocalChecks() error {
 	}))
 }
 
+// BootstrapSELinux configures SELinux on a node prior to installation
+func (i *InstallConfig) BootstrapSELinux(ctx context.Context, printer utils.Printer) error {
+	if !i.SELinux || i.FromService || i.Mode == constants.InstallModeInteractive || i.Remote {
```
Comment (r0mant) [inline tool/gravity/cli/config.go]: Nit: `if i.shouldBootstrapSELinux() {`?

File: tool/gravity/cli/config.go [hunk 2]
```diff
@@ -499,6 +502,28 @@ func (i *InstallConfig) RunLocalChecks() error {
...
+	}
+	metadata, err := monitoring.GetOSRelease()
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if !selinux.GetEnabled() {
+		i.WithField(trace.Component, "selinux").Info("SELinux not enabled on host.")
+		i.SELinux = false
+	} else if !libselinux.IsSystemSupported(metadata.ID) {
+		i.WithField("id", metadata.ID).Info("Distribution not supported.")
```
Comment (r0mant) [inline tool/gravity/cli/config.go]: Should this also use "component: selinux" field? Otherwise the logs will just say "distribution not supported" without any indication this is only SELinux-specific.

File: tool/gravity/cli/config.go [hunk 3]
```diff
@@ -829,6 +854,29 @@ func (j *JoinConfig) GetRuntimeConfig() proto.RuntimeConfig {
 	}
 }
 
+// bootstrapSELinux configures SELinux on a node prior to join
+func (j *JoinConfig) bootstrapSELinux(ctx context.Context, printer utils.Printer) error {
+	if !j.SELinux || j.FromService {
```
Comment (r0mant) [inline tool/gravity/cli/config.go]: Nit: `j.shouldBootstrapSELinux()`.

File: tool/gravity/cli/config.go [hunk 4]
```diff
@@ -829,6 +854,29 @@ func (j *JoinConfig) GetRuntimeConfig() proto.RuntimeConfig {
...
+	metadata, err := monitoring.GetOSRelease()
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	logger := log.WithField(trace.Component, "selinux")
+	if !selinux.GetEnabled() {
+		logger.Info("SELinux not enabled on host.")
+		j.SELinux = false
+	} else if !libselinux.IsSystemSupported(metadata.ID) {
+		logger.WithField("id", metadata.ID).Info("Distribution not supported.")
```
Comment (r0mant) [inline tool/gravity/cli/config.go]: Add "selinux" trace component.

File: tool/gravity/cli/config.go [hunk 5]
```diff
@@ -874,6 +923,28 @@ func (r *autojoinConfig) checkAndSetDefaults() error {
 	return nil
 }
 
+// bootstrapSELinux configures SELinux on a node prior to join
+func (j *autojoinConfig) bootstrapSELinux(ctx context.Context, printer utils.Printer) error {
```
Comment (r0mant) [inline tool/gravity/cli/config.go]: Same two comments as above really.

**Review by r0mant — APPROVED** [review]
