### PR TITLE
Check for conflicts between host and overlay or service networks

### LINKED ISSUE #867: [FEATURE] Add check for conflicts between host network config and overlay network
From a slack chat:
```
Hi, Can you please consider to add a check while gravity installation so if my host has the same ip address like the '—service-cidr' or ‘pod-network-cidr’ it will exit with error
For example, I had the default service cidr which is ‘10.100.0.0/16’ and my host was in 10.100.0.21 which cause to several issues like dns problem and in gravity status: ‘docker-registry (healtz check failed: Get https://leader.telekube.local:5000/v2/: net/http: request canceled while waiting for connection (client.Timeout exceeded while awaiting headers))’ (edited) 
```

### PR DESCRIPTION
**Pull request by lenko-d**
## Description

* This PR adds a check for overlapping values between host and overlay or service networks.
* The check is performed during install and aborts the install if the host IP is in the range of the service or overlay networks.
* The check is also performed during resource config update operation performed on a live cluster
* The check is needed because having overlapping values creates problems. Example problems could be 
 DNS issues or healtz check failure.

## Type of change

* New feature (non-breaking change which adds functionality)
* This change has a user-facing impact

## Linked tickets and other PRs

* Closes https://github.com/gravitational/gravity/issues/867
* Requires https://github.com/gravitational/gravity/pull/2208

## TODOs

- [X] Self-review the change
- [X] Write tests
- [X] Perform manual testing
- [X] Address review feedback

## Testing done

Verified manually from the command line. Passed values that are in the range of the cidrs and got the expected error messages below. 
Also tested with the default values of the cidrs.

```
sudo ./gravity install    --config=config.yaml             --token=secret     

Starting installer
[ERROR]: The selected advertise address 172.16.76.130 conflicts with the service network CIDR range 172.16.76.128/26. Please specify a different service CIDR.


config.yaml:

kind: ClusterConfiguration
version: v1
spec:
  global:
    serviceCIDR:  "172.16.76.129/16"
    podCIDR: "173.16.76.129/16"



```

```
$ sudo gravity resource create config.yaml
[ERROR]: The advertise address 172.31.78.148 conflicts with the service network CIDR range 172.31.78.148/16. Please specify a different service CIDR.


the config.yaml file has the following:

kind: ClusterConfiguration
version: v1
spec:
  global:
    serviceCIDR:  "172.31.78.148/16"
    podCIDR: "173.31.78.148/16"

``` 

---

```
sudo ./gravity install         --advertise-addr=172.31.74.157         --token=secret         --service-cidr=172.31.74.128/26         --pod-network-cidr=172.31.74.128/26         --cloud-provider=aws
Thu Oct  8 14:53:43 UTC	Starting installer
[ERROR]: The selected advertise address 172.31.74.157 conflicts with the service network CIDR range 172.31.74.128/26. Please specify a different service CIDR via --service-cidr flag.

```
---

```
sudo ./gravity install         --advertise-addr=172.31.74.157         --token=secret         --service-cidr=172.31.75.128/26         --pod-network-cidr=172.31.74.128/26         --cloud-provider=aws
Thu Oct  8 15:00:00 UTC	Starting installer
[ERROR]: The selected advertise address 172.31.74.157 conflicts with the pod network CIDR range 172.31.74.128/26. Please specify a different pod CIDR via --pod-network-cidr flag.

```

### CODE REVIEW

File: tool/gravity/cli/config.go [hunk 1]
```diff
@@ -335,6 +335,11 @@ func (i *InstallConfig) CheckAndSetDefaults() (err error) {
 	if err := checkLocalAddr(i.AdvertiseAddr); err != nil {
 		return trace.Wrap(err)
 	}
+
+	if err := checkOverlayNet(i.AdvertiseAddr, i.ServiceCIDR, i.PodCIDR); err != nil {
```
Comment (a-palchikov) [inline tool/gravity/cli/config.go:339]: These command line options is not the only way to configure service/pod subnets - ClusterConfiguration resource is another way to set these up.
During installation these options get merged with an optional cluster configuration resource which then gets validated as a whole. I now spotted a problem that the [PR](https://github.com/gravitational/gravity/pull/1975/) which introduced these changes was not ported to master which I would do before doing these changes.

File: tool/gravity/cli/config.go [hunk 2]
```diff
@@ -1352,6 +1357,33 @@ func checkLocalAddr(addr string) error {
...
+	_, serviceSubnet, err := net.ParseCIDR(serviceCIDR)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	ip := net.ParseIP(advertiseAddr)
+	if ip == nil {
+		return trace.BadParameter("unable to parse advertiseAddr(%s) ", advertiseAddr)
+	}
+	if serviceSubnet.Contains(ip) {
+		return trace.BadParameter("advertiseAddr(%s) is in range of the serviceCIDR %s",
```
Comment (r0mant) [inline tool/gravity/cli/config.go:1371]: Keep in mind that these errors will be shown in a terminal so try to make them easily understandable by an average user and helpful by providing possible resolution advice, for example:

```
The selected advertise address %v conflicts with the service network CIDR range %v.
Please specify a different service CIDR via --service-cidr flag.
```

Same for other error messages here.

File: tool/gravity/cli/config.go [hunk 3]
```diff
@@ -1352,6 +1357,33 @@ func checkLocalAddr(addr string) error {
 		addr, strings.Join(availableAddrs, ", "))
 }
 
+// checkOverlayNet verifies that the host network address is not in the range of the serviceCIDR or podCIDR
+func checkOverlayNet(advertiseAddr string, serviceCIDR string, podCIDR string) error {
```
Comment (r0mant) [inline tool/gravity/cli/config.go:1361]: I think that in addition to checking the advertise address itself we also need to check other network interfaces on the node in case of the multi-homed node? @knisbet What do you think?

File: tool/gravity/cli/config.go (hunk 1 above)
Comment (r0mant) [inline tool/gravity/cli/config.go:339]: Nit: "overlay" usually refers only to the pod network, not service network, so I'd rename this method to something more generic, e.g. `checkNetworkConflict` or something.

**Review by r0mant — COMMENTED** [review]
When we settle on the final implementation, please also write a unit test for this conflict checking logic, I think it'd be useful to have.

File: tool/gravity/cli/config.go (hunk 1 above)
Comment (a-palchikov) [reply tool/gravity/cli/config.go:339]: I submitted https://github.com/gravitational/gravity/pull/2208 to backport changes and I'd like this PR to go after.

**Comment by a-palchikov** [comment]
I've merged the https://github.com/gravitational/gravity/pull/2208 with service CIDR changes so this PR can be updated to verify the unified CIDR configuration.

File: tool/gravity/cli/config.go (hunk 3 above)
Comment (knisbet) [reply tool/gravity/cli/config.go]: I think this gets into rabbit hole territory in the context of detecting conflicts via cluster configuration on a presumably running cluster. For overlay network conflicts it's probably feasible, since the overlay network doesn't get created on any virtual interfaces in the host network namespace. Although there might be alternate implementations out their that would show an interface in the host NS we don't expect. 

Pod cidr would be a whole lot harder, as on a running cluster there may be interfaces assigned within the range on the host (think the flannel bridge). While we can probably control for our own interfaces, this would conflict if anyone tries to use their own CNI plugin. 

So my 2 cents would be to go with the minimal implementation for now. I think to properly check all network interfaces, would require some attention to detail, to only filter to say non virtual / non internal interfaces.

File: lib/validate/net.go [hunk 4]
```diff
@@ -22,6 +22,25 @@ import (
 	"github.com/gravitational/trace"
 )
 
+// NetworkOverlap verifies that ipAddr is not in the range of the subnetCIDR
+func NetworkOverlap(ipAddr string, subnetCIDR string, errMsg string) error {
```
Comment (r0mant) [inline lib/validate/net.go:26]: Nit: Could you shorter form here since all arguments are of the same type:

```go
func NetworkOverlap(ipAddr, subnetCIDR, errMsg string) error {
```

File: lib/validate/net.go [hunk 5]
```diff
@@ -22,6 +22,25 @@ import (
...
+	_, subNet, err := net.ParseCIDR(subnetCIDR)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	ip := net.ParseIP(ipAddr)
+	if ip == nil {
+		return trace.BadParameter("Invalid IP address (%v).", ipAddr)
```
Comment (r0mant) [inline lib/validate/net.go:34]: Nit: Usually, we don't capitalize/dot error messages for better embedding ([error strings](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)). An exception would be when the error represents a full message that will be displayed to a user.

```go
return trace.BadParameter("invalid IP address (%v)", ipAddr)
```

File: tool/gravity/cli/clusterconfig.go [hunk 6]
```diff
@@ -280,7 +281,26 @@ func validateClusterConfig(localEnv *localenv.LocalEnvironment, update libcluste
...
 	}
-	return validate.ClusterConfiguration(existing, update)
+	err = validate.ClusterConfiguration(existing, update)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	server, err := findLocalServer(cluster.ClusterState.Servers)
+	if err != nil {
+		return trace.NotFound("unable to find server info")
```
Comment (r0mant) [inline tool/gravity/cli/clusterconfig.go:291]: I would make the error more helpful for potential troubleshooting i.e. "unable to find local node among cluster state servers: %v".

File: tool/gravity/cli/clusterconfig.go [hunk 7]
```diff
@@ -280,7 +281,26 @@ func validateClusterConfig(localEnv *localenv.LocalEnvironment, update libcluste
...
+	}
+	if err := validate.NetworkOverlap(server.AdvertiseIP, update.GetGlobalConfig().ServiceCIDR, fmt.Sprintf("The advertise address %v conflicts with the service network CIDR range %v. Please specify a different service CIDR.",
+		server.AdvertiseIP, update.GetGlobalConfig().ServiceCIDR)); err != nil {
+		return trace.Wrap(err)
+	}
+
+	if err := validate.NetworkOverlap(server.AdvertiseIP, update.GetGlobalConfig().PodCIDR, fmt.Sprintf("The advertise address %v conflicts with the pod network CIDR range %v. Please specify a different pod CIDR.",
```
Comment (r0mant) [inline tool/gravity/cli/clusterconfig.go:298]: Nit: I would move the message into a separate variable so the lines are shorter and code is easier to read. As a rule of thumb, I use 80-100 characters as a cut-off point for a line length.

```go
message := fmt.Sprintf("xxx", ...)
if err := validate.NetworkOverlap(xxx, yyy, message); err != nil {
```

This applies to all 4 places where this is called.

**Review by r0mant — APPROVED** [review]
Mostly stylistic nits, otherwise lgtm.

**Comment by r0mant** [comment]
@lenko-d Once merged, let's please backport this to 7.0 as well.

File: lib/validate/net.go (hunk 5 above)
Comment (a-palchikov) [inline lib/validate/net.go:34]: nit: `Invalid` should not be capitalized in the error message.

File: lib/validate/net_test.go [hunk 8]
```diff
@@ -73,3 +73,40 @@ func (*S) TestValidateKubernetesSubnets(c *check.C) {
...
+			ipAddr:      "11.100.0.111",
+			subnetCIDR:  "10.100.0.0/16",
+			ok:          true,
+			description: "Outside the range.",
+		},
+	}
+	for _, tc := range testCases {
+		err := NetworkOverlap(tc.ipAddr, tc.subnetCIDR, "errMsg")
+		if tc.ok {
+			c.Assert(err, check.IsNil, check.Commentf(tc.description))
```
Comment (a-palchikov) [inline lib/validate/net_test.go:107]: Ideally this should verify that the err is also an expected one. You could used ErrorMatches checker instead.

File: tool/gravity/cli/config.go [hunk 9]
```diff
@@ -349,6 +349,17 @@ func (i *InstallConfig) CheckAndSetDefaults(validator resources.Validator) (err
 	if err := checkLocalAddr(i.AdvertiseAddr); err != nil {
 		return trace.Wrap(err)
 	}
+
+	if err := validate.NetworkOverlap(i.AdvertiseAddr, i.ServiceCIDR, fmt.Sprintf("The selected advertise address %v conflicts with the service network CIDR range %v. Please specify a different service CIDR via --service-cidr flag.",
```
Comment (a-palchikov) [inline tool/gravity/cli/config.go:353]: Like I hinted at previously, this will miss the service/pod CIDR configuration coming from a resource file. I'd look into [validateResources](https://github.com/gravitational/gravity/blob/version/7.0.x/tool/gravity/cli/config.go#L650) instead.

**Review by a-palchikov — APPROVED** [review]
