### PR TITLE
[5.5] unpack application resources without the 'resources' directory

### LINKED ISSUE #452: [BUG] app that contains resources directory cannot install
**Describe the bug**

If the root directory of a gravity app contains a resources subdirectory, the built application will not install.

```
/app.yaml
/resources
/resources/something.yaml
```

**To Reproduce**

Download quickstart reference
Add resources directory: `mkdir mattermost/resources/resources`
Add file: 
```
cat mattermost/resources/resources/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
```
Build app: `tele build -o mattermost.tar mattermost/resources/app.yaml`
Install built app.

**Expected behavior**

The install to complete successfully

**Logs**

The init container for the install hook fails with the following logs:
```
kevin-test1:/$ kctl logs install-50bbd4-5pgpx -c init
gravitational.io/mattermost:2.2.0 unpacked at /var/lib/gravity/resources
mv: can't rename '/var/lib/gravity/resources/resources/charts': Directory not empty
mv: can't rename '/var/lib/gravity/resources/resources/resources': Directory not empty
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Ubuntu 16.04
 - Gravity [e.g. 5.5.4]: 6.0.0-rc.1
 - Platform [e.g. Vmware, AWS]: GCE (local provider)

**Additional context**

The install logs should probably pull the init container logs if the installer see's the init container failing.

### PR DESCRIPTION
**Pull request by a-palchikov**
In #452, if the application resource directory itself contains a `resources` sub-directory, hook init containers fail.
To fix this, this PR changes the semantics of `app unpack` sub-command to unpack application resources from the tarball's `resources` directory directly into the specified directory without the `resources` directory itself. This should be a safe (and sensible!) change as the hook's init container code is the only client of `app unpack`.

Fixes #452.

### CODE REVIEW

File: tool/gravity/cli/app.go [hunk 1]
```diff
@@ -424,7 +424,7 @@ func unpackAppResources(env *localenv.LocalEnvironment, loc loc.Locator, dir, op
 		}
 		defer reader.Close()
 
-		if err := dockerarchive.Untar(reader, dir, archive.DefaultOptions()); err != nil {
+		if err := archive.ExtractGlob(reader, dir, "resources", []string{"*"}); err != nil {
```
Comment (r0mant) [inline tool/gravity/cli/app.go]: Nit: `defaults.ResourcesDir`?

File: lib/archive/archive.go [hunk 2]
```diff
@@ -109,13 +109,31 @@ func Extract(r io.Reader, dir string) error {
...
 }
 
+// ExtractGlob extracts the contents of the specified tarball under directory dir.
+// Only the files/directories found in tarDir in the tarball matching patterns are extracted.
+// Note, files from tarDir are written directly to dir omitting tarDir.
+// The resulting files and directories are created using the current user context.
+func ExtractGlob(r io.Reader, dir, tarDir string, patterns []string) error {
+	return trace.Wrap(TarGlob(tar.NewReader(r), tarDir, patterns, func(tarRelPath string, header *tar.Header, f *tar.Reader) error {
+		// Security: ensure tar doesn't refer to file paths outside the directory
+		err := SanitizeTarPath(header, dir)
```
Comment (r0mant) [inline lib/archive/archive.go]: Nit: I'd try to be consistent with how err is handled at least in the same function, i.e. let's use either

```go
if err := xxx(); err != nil {
```

style or

```go
err := xxx()
if err != nil {
```

in both places.

File: tool/gravity/cli/app.go (hunk 1 above)
Comment (r0mant) [inline tool/gravity/cli/app.go]: Also, should the "default" directory (if dir is empty) above be updated to include "resources" directory?

```go
if dir == "" {
	unpackedDir := filepath.Join(env.StateDir, defaults.PackagesDir, defaults.UnpackedDir)
	dir = pack.PackagePath(unpackedDir, loc)
}
```

Comment (a-palchikov) [reply tool/gravity/cli/app.go]: I'd rather have directory argument mandatory.

File: lib/archive/archive.go [hunk 3]
```diff
@@ -109,13 +109,42 @@ func Extract(r io.Reader, dir string) error {
...
+// Note, files from tarDir are written directly to dir omitting tarDir.
+// The resulting files and directories are created using the current user context.
+func ExtractWithPrefix(r io.Reader, dir, tarDirPrefix string) error {
+	err := TarGlobWithPrefix(tar.NewReader(r), tarDirPrefix, func(match *tar.Header, r *tar.Reader) error {
+		relpath, err := filepath.Rel(tarDirPrefix, match.Name)
+		if err != nil {
+			return trace.Wrap(err)
+		}
+		// Security: ensure tar doesn't refer to file paths outside the directory
+		err = validPath(relpath, dir, "invalid file path")
```
Comment (knisbet) [inline lib/archive/archive.go]: I think my only worry is, that this replicates other sanitization code, which leaves some risk if something new is discovered missing in the tar sanitization, that the semi-duplicate code get's missed. I see why it was separated out, that's just my only thought on the risks of doing it this way.

Comment (a-palchikov) [reply lib/archive/archive.go]: I updated to keep using `SanitizeTarPath` as is.
