### PR TITLE
[6.1.x] always create ClusterConfiguration resource on install

### LINKED ISSUE #1863: 6.1.30 install panics on service cidr
### Description

**What happened**:

Install with Gravity 6.1.30 is crashing on the `/configure` phase.

```
ubuntu@node-1:~/installer$ sudo -E ./gravity install --advertise-addr=192.168.99.102 --cluster=test
Sun Jul 12 16:30:33 UTC	Starting enterprise installer

To abort the installation and clean up the system,
press Ctrl+C two times in a row.

If you get disconnected from the terminal, you can reconnect to the installer
agent by issuing 'gravity resume' command.

If the installation fails, use 'gravity plan' to inspect the state and
'gravity resume' to continue the operation.
See https://gravitational.com/gravity/docs/cluster/#managing-an-ongoing-operation for details.

Sun Jul 12 16:30:33 UTC	Connecting to installer
Sun Jul 12 16:30:48 UTC	Connected to installer
Sun Jul 12 16:30:49 UTC	Successfully added "node" node on 192.168.99.102
Sun Jul 12 16:30:49 UTC	All agents have connected!
Sun Jul 12 16:30:49 UTC	Operation has been created
Sun Jul 12 16:30:50 UTC	Executing "/checks" locally
Sun Jul 12 16:30:50 UTC	Running pre-flight checks
Sun Jul 12 16:30:50 UTC	Execute preflight checks
Sun Jul 12 16:30:51 UTC	Executing "/configure" locally
Sun Jul 12 16:30:51 UTC	Configuring cluster packages
Sun Jul 12 16:30:51 UTC	Configure packages for all nodes
Sun Jul 12 16:30:52 UTC	Saving debug report to /home/ubuntu/installer/crashreport.tgz
[ERROR]: failed to execute phase "/configure"
	EOF
```

**What you expected to happen**:

Install should work.

**How to reproduce it (as minimally and precisely as possible)**:

```
2020-07-12T16:30:52Z INFO             2020/07/12 16:30:52 http: panic serving 192.168.99.102:36894: runtime error: invalid memory address or nil pointer dereference utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             goroutine 327 [running]: utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             net/http.(*conn).serve.func1(0xc000eb14a0) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/net/http/server.go:1769 +0x139" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             panic(0x32f6780, 0x6a50a40) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/runtime/panic.go:522 +0x1b5" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opsservice.planetConfig.serviceSubnet(0xc00145f83a, 0x6, 0xc00100d140, 0x1a, 0xc00145f840, 0x8, 0xc00145f860, 0x6, 0xc00145f848, 0x7, ...) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opsservice/configure.go:1044 +0x3f" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opsservice.(*site).configurePackages(0xc000598c80, 0xc000598dc0, 0xc000b9a519, 0x24, 0xc000b9a544, 0x4, 0xc000b9a55b, 0x24, 0x0, 0x0, ...) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opsservice/configure.go:370 +0x9b3" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opsservice.(*Operator).ConfigurePackages(0xc000e441e0, 0xc000b9a519, 0x24, 0xc000b9a544, 0x4, 0xc000b9a55b, 0x24, 0x0, 0x0, 0x0, ...) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opsservice/configure.go:106 +0x64e" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opsroute.(*Router).ConfigurePackages(0xc000ad48a0, 0xc000b9a519, 0x24, 0xc000b9a544, 0x4, 0xc000b9a55b, 0x24, 0x0, 0x0, 0x0, ...) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opsroute/forward.go:516 +0xf4" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops.(*OperatorACL).ConfigurePackages(0xc000b30f80, 0xc000b9a519, 0x24, 0xc000b9a544, 0x4, 0xc000b9a55b, 0x24, 0x0, 0x0, 0x0, ...) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/operatoracl.go:657 +0x120" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opshandler.(*WebHandler).configurePackages(0xc000bae3c0, 0x3f46600, 0xc000ed9c00, 0xc00107a700, 0xc000b7fb00, 0x3, 0x3, 0xc000b31000, 0xc000422101, 0xc000b31080) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opshandler/opshandler.go:1581 +0x25d" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opshandler.NeedsAuth.func1(0x3f46600, 0xc000ed9c00, 0xc00107a600, 0xc000b7fb00, 0x3, 0x3, 0x20, 0x203000) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opshandler/opshandler.go:2422 +0x1c8" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/ops/opshandler.NeedsAuth.func2(0x3f46600, 0xc000ed9c00, 0xc00107a600, 0xc000b7fb00, 0x3, 0x3) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/ops/opshandler/opshandler.go:2429 +0x88" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000bae3c0, 0x3f46600, 0xc000ed9c00, 0xc00107a600) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6d1" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x3f46600, 0xc000ed9c00, 0xc00107a600, 0xc000ca19e0, 0x1, 0x1) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter/router.go:237 +0x4d" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000bee150, 0x3f46600, 0xc000ed9c00, 0xc00107a600) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6d1" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             github.com/gravitational/gravity/lib/httplib.GRPCHandlerFunc.func1(0x3f46600, 0xc000ed9c00, 0xc00107a600) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/gopath/src/github.com/gravitational/gravity/lib/httplib/http.go:187 +0xc8" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             net/http.HandlerFunc.ServeHTTP(0xc000bee450, 0x3f46600, 0xc000ed9c00, 0xc00107a600) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/net/http/server.go:1995 +0x44" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             net/http.serverHandler.ServeHTTP(0xc0006f96c0, 0x3f46600, 0xc000ed9c00, 0xc00107a600) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/net/http/server.go:2774 +0xa8" utils/logginghook.go:56
2020-07-12T16:30:52Z ERRO             Phase execution failed: EOF. phase:/configure utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             net/http.(*conn).serve(0xc000eb14a0, 0x3f62040, 0xc0007a5340) utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/net/http/server.go:1878 +0x851" utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             created by net/http.(*Server).Serve utils/logginghook.go:56
2020-07-12T16:30:52Z INFO             "\t/go/src/net/http/server.go:2884 +0x2f4" utils/logginghook.go:56
2020-07-12T16:30:52Z DEBU [FSM:INSTA] Applied StateChange(Phase=/configure, State=failed, Error=EOF). opid:8965c381-8c47-4937-872c-369ecdd3c533 utils/logginghook.go:56
2020-07-12T16:30:52Z WARN [INSTALLER] Failed to execute operation plan. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError EOF
Stack Trace:
	/gopath/src/github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/httplib/httplib.go:110 github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/gopath/src/github.com/gravitational/gravity/lib/ops/opsclient/opsclient.go:1585 github.com/gravitational/gravity/lib/ops/opsclient.(*Client).PostJSON
	/gopath/src/github.com/gravitational/gravity/lib/ops/opsclient/opsclient.go:904 github.com/gravitational/gravity/lib/ops/opsclient.(*Client).ConfigurePackages
	/gopath/src/github.com/gravitational/gravity/lib/install/phases/configure.go:69 github.com/gravitational/gravity/lib/install/phases.(*configureExecutor).Execute
	/gopath/src/github.com/gravitational/gravity/lib/fsm/fsm.go:524 github.com/gravitational/gravity/lib/fsm.(*FSM).executeOnePhase
	/gopath/src/github.com/gravitational/gravity/lib/fsm/fsm.go:456 github.com/gravitational/gravity/lib/fsm.(*FSM).executePhaseLocally
	/gopath/src/github.com/gravitational/gravity/lib/fsm/fsm.go:416 github.com/gravitational/gravity/lib/fsm.(*FSM).executePhase
	/gopath/src/github.com/gravitational/gravity/lib/fsm/fsm.go:261 github.com/gravitational/gravity/lib/fsm.(*FSM).ExecutePhase
	/gopath/src/github.com/gravitational/gravity/lib/fsm/fsm.go:175 github.com/gravitational/gravity/lib/fsm.(*FSM).ExecutePlan
	/gopath/src/github.com/gravitational/gravity/lib/install/operation.go:81 github.com/gravitational/gravity/lib/install.(*Installer).ExecuteOperation
	/gopath/src/github.com/gravitational/gravity/lib/install/engine/cli/cli.go:108 github.com/gravitational/gravity/lib/install/engine/cli.(*Engine).execute
	/gopath/src/github.com/gravitational/gravity/lib/install/engine/cli/cli.go:80 github.com/gravitational/gravity/lib/install/engine/cli.(*Engine).Execute
	/gopath/src/github.com/gravitational/gravity/lib/install/install.go:258 github.com/gravitational/gravity/lib/install.(*Installer).execute
	/gopath/src/github.com/gravitational/gravity/lib/install/install.go:206 github.com/gravitational/gravity/lib/install.(*Installer).startExecuteLoop.func1
	/go/src/runtime/asm_amd64.s:1337 runtime.goexit
User Message: failed to execute phase &#34;/configure&#34;
	EOF] utils/logginghook.go:56
```

### Environment

 - Gravity version [e.g. 7.0.11]: 6.1.30

### PR DESCRIPTION
**Pull request by a-palchikov**
## Description

 * Add guard blocks to avoid use of nil interface
 * Always generate cluster configuration based on CLI flags even if only from default values
 * Include pod/service CIDR values in text output of 'gravity resource    get'

## Type of change

* Bug fix (non-breaking change which fixes an issue)
* Regression fix (non-breaking change which fixes a regression)
* This change has a user-facing impact

## Linked tickets and other PRs

* Closes #1863
* Requires https://github.com/gravitational/gravity.e/pull/4312

## TODOs

- [x] Self-review the change
- [ ] Write tests
- [x] Perform manual testing
- [ ] Address review feedback

## Testing done

Since I'm testing on GCE, I had to embed alternative logic to turn off ClusterConfiguration generation as there was always input in that case (e.g. the cloud provider was not empty).
Otherwise, the error can only be triggered with `6.1.30` on an on-prem node that is not running on a known cloud provider (either AWS or GCE).

### Install without implicit cluster configuration (e.g. cloud provider):
```
$ ./gravity install --advertise-addr=10.128.0.18 --cluster=dev.test --token=secret-token
```
Ensure the installation is successful.

### Install with implicit cluster configuration (e.g. cloud provider):
```
$ ./gravity install --advertise-addr=10.128.0.18 --cluster=dev.test --token=secret-token --cloud-provider=generic
```
Ensure the installation is successful.

### Install with explicit cluster configuration:
```
$ cat ./servicecidr.yaml
kind: ClusterConfiguration
version: v1
spec:
  global:
    # CIDR range for Services in Cluster
    serviceCIDR: "10.200.0.0/16"
$ ./gravity install --advertise-addr=10.128.0.18 --cluster=dev.test --token=secret-token --cloud-provider=generic --config=./servicecidr.yaml
```
Ensure the installation is successful.

### CODE REVIEW

File: lib/install/config.go [hunk 1]
```diff
@@ -103,10 +103,6 @@ type Config struct {
 	Mounts map[string]string
 	// DNSOverrides contains installer node DNS overrides
 	DNSOverrides storage.DNSOverrides
-	// PodCIDR is a pod network CIDR
```
Comment (a-palchikov) [inline lib/install/config.go:106]: Removed this in favor of moving the corresponding values to `ClusterConfiguration` resource.

File: tool/gravity/cli/config.go [hunk 2]
```diff
@@ -157,9 +158,22 @@ type InstallConfig struct {
...
 	// AcceptEULA allows to auto-accept end-user license agreement.
 	AcceptEULA bool
+
+	// Computed values
+	//
 	// writeStateDir is the directory where installer stores state for the duration
 	// of the operation
 	writeStateDir string
+	// app is the application being installed
+	app *app.Application
```
Comment (a-palchikov) [inline tool/gravity/cli/config.go:168]: Moved to top-level installer configuration to enable early validation - otherwise, if the configuration is validated in the server component, the error is a cryptic:
```
service 'gravity-installer.service' has failed. Check journal log for details.
```

File: tool/gravity/cli/config.go [hunk 3]
```diff
@@ -355,52 +401,14 @@ func (i *InstallConfig) NewInstallerConfig(
 	env *localenv.LocalEnvironment,
 	wizard *localenv.RemoteEnvironment,
 	process process.GravityProcess,
```
Comment (a-palchikov) [inline tool/gravity/cli/config.go:403]: We still to run some tasks in the server as it's when it has access to the wizard operator.

File: tool/gravity/cli/config.go [hunk 4]
```diff
@@ -608,6 +630,21 @@ func (i *InstallConfig) updateClusterConfig(resources []storage.UnknownResource)
 	if globalConfig.CloudProvider != "" {
 		i.CloudProvider = globalConfig.CloudProvider
 	}
+	if i.ServiceCIDR != "" && globalConfig.ServiceCIDR == "" {
+		globalConfig.ServiceCIDR = i.ServiceCIDR
+	}
+	if i.PodCIDR != "" && globalConfig.PodCIDR == "" {
+		globalConfig.PodCIDR = i.PodCIDR
+	}
+	globalConfig.PodCIDR, err = validate.NormalizeSubnet(globalConfig.PodCIDR)
```
Comment (a-palchikov) [inline tool/gravity/cli/config.go:639]: Turn user's `10.244.0.10/16` -> `10.244.0.0/16`. This definitely makes sense for service IP range (since API server will still use the first IP starting from `10.244.0.0` and not `10.244.0.10`) so I duplicated the same for pod IP range.

File: lib/ops/opsservice/configure.go [hunk 5]
```diff
@@ -323,9 +323,11 @@ func (s *site) configurePackages(ctx *operationContext, req ops.ConfigurePackage
 		if err != nil {
 			return trace.Wrap(err)
 		}
-		if s.cloudProviderName() != "" {
-			clusterConfig.SetCloudProvider(s.cloudProviderName())
-		}
+	} else {
+		clusterConfig = clusterconfig.NewEmpty()
```
Comment (r0mant) [inline lib/ops/opsservice/configure.go:327]: Nit: Instead of `else` block you could've probably just initialize empty clusterConfig above.

```go
clusterConfig := clusterconfig.NewEmpty()
if len(req.Config) != 0 {
  clusterConfig, err = clusterconfig.Unmarshal(req.Config)
  ...
}
```

File: tool/gravity/cli/config.go (hunk 2 above)
Comment (r0mant) [inline tool/gravity/cli/config.go:168]: I would make this a value instead of a pointer, to avoid potential panics if the caller doesn't check this for non-nil.

**Review by r0mant — APPROVED** [review]
@a-palchikov So this wasn't caught by robotest because it installs in the cloud integration mode, not bare metal? If so, we should add a bare metal mode install test case to robotest. cc @wadells

**Review by knisbet — APPROVED** [review]

**Comment by wadells** [comment]
> @a-palchikov So this wasn't caught by robotest because it installs in the cloud integration mode, not bare metal? If so, we should add a bare metal mode install test case to robotest. cc @wadells

versions/6.1.x is using Robotest 2.0, which has:

https://github.com/gravitational/robotest/blob/v2.0.0/infra/gravity/node_commands.go#L275

If anything, we may want to add flex to this and exercise the integrations, but that isn't on the roadmap until the AWS work.

**Comment by r0mant** [comment]
@a-palchikov @wadells If we do install with generic cloud provider in robotest, I wonder why this wasn't caught then? Is that just by the virtue of the nodes being GCE nodes, even if installing with generic provider?

File: tool/gravity/cli/config.go (hunk 2 above)
Comment (a-palchikov) [reply tool/gravity/cli/config.go:168]: The point of handling this is pretty limited so a somewhat skilled coder can manage to avoid the nil pointer. It is also exacerbated by the fact that `lib/install.Config.App` is a pointer attribute to validate that it's been properly set - not sure which pattern is better here - using a value and some way to tell an empty struct from a non-empty one or leaving a pointer...

**Comment by a-palchikov** [comment]
@r0mant @wadells yes, we test as onprem on robotest. As I've written above, the problem is with bare-metal using onprem vs CGE using onprem as in the latter case, the cluster configuration was partially populated (i.e. you had to specify the cloud-provider to disable auto-detection) hence giving no errors during robotests.

File: tool/gravity/cli/config.go (hunk 2 above)
Comment (r0mant) [reply tool/gravity/cli/config.go:168]: Ok, sounds good.
