### PR TITLE
(7.1) Better errors for teleport nodes pre-check

### LINKED ISSUE #1817: Add Teleport nodes pre-upgrade check
Before triggering the upgrade, Gravity should check whether all Teleport nodes are available and bail out with a clear error message if some of them aren't and instructions of what to check.

Success:

- [ ] `gravity upgrade` reports a clear error if some Teleport nodes are unavailable, rather than just failing to deploy agents.
- [ ] If upgrading from `5.5.40`, show a link to a [KB article](https://community.gravitational.com/t/recover-teleport-nodes-failing-to-join-due-to-bad-token/649) that explains how to recover from [regression](https://github.com/gravitational/gravity/issues/1445).

### PR DESCRIPTION
**Pull request by r0mant**
## Description

Forward-port: https://github.com/gravitational/gravity/pull/1874.

## Type of change

* Internal change (not necessarily a bug fix or a new feature)

## Linked tickets and other PRs

* Closes https://github.com/gravitational/gravity/issues/1817.
* Ports https://github.com/gravitational/gravity/pull/1874.

### CODE REVIEW

File: lib/ops/opsservice/versions.go [hunk 1]
```diff
@@ -255,3 +255,12 @@ const (
...
 Please rebuild it as described in https://gravitational.com/gravity/docs/cluster/#direct-upgrades-from-older-lts-versions.`
 )
+
+var (
+	// TeleportBrokenJoinTokenVersion is version of the release affected by
+	// the issue with Teleport using incorrect auth token on joined nodes.
+	//
+	// Github issue: https://github.com/gravitational/gravity/issues/1445.
+	// KB: https://community.gravitational.com/t/recover-teleport-nodes-failing-to-join-due-to-bad-token/649.
+	TeleportBrokenJoinTokenVersion = semver.New("5.5.40")
```
Comment (a-palchikov) [inline lib/ops/opsservice/versions.go:265]: This won't matter for master as long as we have not ported intermediate upgrades?

**Review by a-palchikov — APPROVED** [review]

File: lib/ops/opsservice/versions.go (hunk 1 above)
Comment (r0mant) [reply lib/ops/opsservice/versions.go:265]: Yeah, probably doesn't make sense to have this specific check for anything beyond 7.0. I'll remove it from master's port.
